# [package]
# name = "rust-typescript-ast-parsing"
# version = "0.1.0"
# edition = "2024"

# [dependencies]

[workspace]
resolver = "2" # 2021
members = [
    "crates/analysis",
    "crates/validation",
    "crates/parser",
    "crates/reporting",
    "crates/cli",
]


