[package]
name = "cli"
edition = "2021"

[[bin]]
name = "ts-validator"
path = "src/main.rs"

[dependencies]
analysis = { path = "../analysis" }
validation = { path = "../validation" }
parser = { path = "../parser" }
reporting = { path = "../reporting" }
clap = { workspace = true }