[package]
name = "parser"
edition = "2021"

[dependencies]
walkdir = "2"
clap = { workspace = true }
swc_ecma_ast = { workspace = true }
swc_ecma_parser = { workspace = true }
swc_ecma_visit = { workspace = true }
swc_common = { workspace = true }

[dev-dependencies]
tempfile = "3"