[package]
name = "validation"
edition = "2021"

[dependencies]
clap = { workspace = true }
swc_ecma_ast = { workspace = true }
swc_ecma_visit = { workspace = true }
swc_common = { workspace = true }

[dev-dependencies]
swc_ecma_parser = { workspace = true }